# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UsWkSFwIP_W1Wz7WY6FtdKaqL4RW188Y
"""

import pandas as pd
guruh=pd.DataFrame ({
             'Ism': ['Gulnoza'  , 'Zulayho', 'Mohigul', 'Sardor', 'Durbek'],
             'Familiya': ['Jorayeva', 'Qadamova', 'Abdullayeva', 'Xontorayev', 'Xalilov'],
             'Yashash manzili': [ "Farg'ona shahar" , "Farg'ona shahar", "Farg'ona shahar", "Farg'ona shahar", "Farg'ona shahar"],
             'Fan nomi': [ 'Elektronika va sxemalar' , 'Suniy intellekt', 'Malumotlar tuzilmasi', 'Malumotlar tuzilmasi', 'Suniy intellekt'],
            'Dars soati': [ '180', '180', '180', '180', '180']
})
print(guruh)

guruh.to_excel('guruh.xlsx')